version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 99
    reviewers:
      - "WikiRik"
  - package-ecosystem: "docker"
    directory: "/docker/network"
    schedule:
      interval: daily
    open-pull-requests-limit: 99
    reviewers:
      - "WikiRik"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 99
    reviewers:
      - "WikiRik"
